### ISSUE TITLE
invalid parent error with resumeJAGS

### ISSUE THREAD

**Issue by qureshlatif** [mikemeredith/saveJAGS#8]
Hi Mike. I am getting an "invalid parent values" error (full error message below) when trying to extend a model run with resumeJAGS. The model ran fine for 50 saves, and I was able to recover the saves, gather the output, and successfully run the `mcmcOutput` function on the recovered saves. I just wanted to extend the run to get a bit more sampling. Any thoughts on why I would be getting this error message after running the model successfully for so long? I can send you the saves in a zip file if you want to look at them, but thought I'd check first if this is a known issue.

> out <- resumeJAGS(fileStub = "saveJAGS/mod_threshold_HZ_TBLO/modSave", nSaves = 30)
Calling recoverSaves to check target folder.
File sizes diverge from the median by 34.5 %
Parallel processing now running; output will be written to files.
Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: Error in node pic[1,1]
Invalid parent values

**Comment by mikemeredith** [comment]
Hi Quresh, Thanks for emailing me the `saveJAGS` output files: I can replicate your error.

The error is coming from JAGS, in the call to `jm$recompile()`. It's not specific to `recompile`; I get the same error if I try `jags.model` using the last values in the old chains (ie, `jm$state()`) as initial values.

In your model you have 
```
pic[j, d] <- pi[j, d] / pcap[j] #  where
pi[j, d] <- (1 - exp(-pow((mdpnt[d] / a[j]), -b))) / 10 # and
pcap[j] <- sum(pi[j, ])
```
With the last values in the chains, the result of `pow()` is very small, ca. 1e-200, so that the value of `exp()` is identically 1 due to underflow, and `pic[1,1]` is thus 0/0.

These errors can be avoided with suitable code (see [here](https://mmeredith.net/blog/2017/UnderOverflow.htm)), and JAGS must use such work-arounds when the chains are running. Either something different happens during initialization, or the values returned as the last values in the chains have lost precision.

`saveJAGS` has code to catch errors in JAGS and to write those to files, allowing chains without errors to run. I didn't put similar code into `resumeJAGS` as I naively assumed that if the model had already run successfully, nothing could go wrong when resumed. I need to fix that.

**Comment by mikemeredith** [comment]
`resumeJAGS` now checks for errors in JAGS and writes them to files.

**Comment by qureshlatif** [comment]
OK, thank you!
Is this a problem that can be avoided by how the model is specified, or is this just something that is going to happen for some datasets/models?
    On Saturday, March 13, 2021, 03:04:00 AM MST, Mike Meredith ***@***.***> wrote:  
 
 


resumeJAGS now checks for errors in JAGS and writes them to files.

**Comment by mikemeredith** [comment]
You can't write code to avoid these errors, primarily because JAGS doesn't allow you to use log(p) in `dbin` or `dbern`, as you can in R's `dbinom`. It also lacks the equivalent of R's `log1p` and `expm1` functions. And JAGS takes care of all that while running, it's just recompilation which fails.

This is really a JAGS bug, so we might draw it to Martyn Plummer's attention, though fixing it might be a major undertaking.

Since you can't resume, the best way to get more draws would be to run more chains. Run the original call to `saveJAGS` again but with `firstChainID="BA"` and a different folder. Move the new .RData files into the old folder and run `recoverSaves`.

**Comment by qureshlatif** [comment]
Makes sense. Thanks for those insights and advice. In this case, my reason for wanting to resume the model is to improve convergence rather than just getting more samples per se, so I imagine adding more chains won't help. It didn't take more than a day to run, however, so starting the model over is perfectly feasible. Good to know for future reference. Hopefully, I don't ever run into this issue with a model that takes weeks to reach convergence. :)
    On Monday, March 15, 2021, 07:59:09 PM MDT, Mike Meredith ***@***.***> wrote:  
 
 


You can't write code to avoid these errors, primarily because JAGS doesn't allow you to use log(p) in dbin or dbern, as you can in R's dbinom. It also lacks the equivalent of R's log1p and expm1 functions. And JAGS takes care of all that while running, it's just recompilation which fails.

This is really a JAGS bug, so we might draw it to Martyn Plummer's attention, though fixing it might be a major undertaking.

Since you can't resume, the best way to get more draws would be to run more chains. Run the original call to saveJAGS again but with firstChainID="BA" and a different folder. Move the new .RData files into the old folder and run recoverSaves.
